### PR TITLE
Requesting Code Review: Intuit Login Form

### PR DESCRIPTION
**Pull request by MFahadUmer**
## Updated Intuit Login Form Clone

In this update we:
- Integrated stickler linter in this repo. 
- Added hover effect on the top-right sign in button.
- Extra styling and CSS modifications for the body, buttons, and form.
- Change the top-right sign in button from <input> tag to <button> tag.
- Change the phone input type from "text" to "tel".
- Added shadow to the buttons.
- Removed inline styling from the Html.
- Additional formatting for the font size and text alignment.
- Linter error corrections

mint-signup-clone

### CODE REVIEW

**Comment by ChristianOtieno** [comment]
Hello team! :tada: Good job with this project. 
There are, however, some minor changes required before we can merge to master.
- General:
1. This project is required to have a descriptive [README](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/descriptive_readme.png) as a [requirement](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/).
- Section Specific:
1. Make sure you pass your markup to the HTML validator and check for errors as required [here](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/section/validation_requirement.png): You can use [Nu Checker](https://validator.w3.org/#validate_by_input) to validate and correct the errors. 
2. Make your page is live and add the live link to the README file. You can use [githack](https://raw.githack.com/) for that.
3. Remove all your inline styling in your markup and move them all to the CSS file. 
- When you have made the specified changes, please submit another code review. Thank you!

**Review by christianotieno — CHANGES_REQUESTED** [review]
### **:warning:CHANGES REQUIRED:warning:**

Hello team! :tada: Good job with this project. 
There are, however, some minor changes required before we can merge to master.
- General:
1. This project is required to have a descriptive [README](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/descriptive_readme.png) as a [requirement](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/).
- Section Specific:
1. Make sure you pass your markup to the HTML validator and check for errors as required [here](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/section/validation_requirement.png): You can use [Nu Checker](https://validator.w3.org/#validate_by_input) to validate and correct the errors. 
2. Make your page is live and add the live link to the README file. You can use [githack](https://raw.githack.com/) for that.
3. Remove all your inline styling in your markup and move them all to the CSS file. 
- When you have made the specified changes, please submit another code review. Thank you!

**Comment by mikenath223** [comment]
**Pull request currently under review by Michgolden Ukeje (TSE).**
Kindly exercise patience 🐱

**Review by mikenath223 — CHANGES_REQUESTED** [review]
### Nice job Team👏👏.

Your frontend is nicely coming to shape @MFahadUmer and @edieatha👍👍
 
However, a few requirements need to be met before proceeding:👇

- [ ] Required - Please fix all linting errors on your CSS. We need to get this mark(❌) on your commit message to turn to this green mark(✅).

- [ ] Required - Also kindly fix this section below [Screenshot]👇:
**This is yours**
ice_screenshot_20200330-192600

**This is the way it should look👇**
ice_screenshot_20200330-193420

- [ ] Required -  Also please take note of the following sections of your page and make them clickable as seen in the original webpage:👇

* The `Sign in` button at the top right-hand corner is meant to be clickable👇
ice_screenshot_20200330-192627

* The `Create Account` button is meant to be clickable👇:
ice_screenshot_20200330-185457

* The three links(`Legal`, `Privacy`, `Security`) at the footer section are also meant to be clickable links:👇
ice_screenshot_20200330-192613

- [ ] Optional - You can consider updating your live version link on your readme by going using the gitHack [tool](https://raw.githack.com/) to generate a new link.

**Awesome job once more team👏**

Kindly fix these issues and request another review👍
Feel free to contact me on slack(michgolden) if you need further clarification.

HAPPY CODING👨‍💻

**Review by MarioDena — APPROVED** [review]
Hello! My name is Mario good work on your project!

## Project approved!

However I would recommend to check your CSS for bad practices. This change is optional since it wasn't commented before, article for help: https://speckyboy.com/good-bad-css-practices/

## Code Review By Mario Enrique Delgado Naranjo

**Comment by MFahadUmer** [comment]
I completed this project with my partner. after completing these projects I received the status of "Project Completed" but my partner didn't receive this status due to these issues my status has been reset and now I've to submit this project / link again here is the email screenshot given below from Greg
image

**Pull request merged**
